"""Convert a PNG into an LVGL 8 image (.c) compiled into the firmware.

  python tools/img2lvgl.py assets/tuna_logo.png tuna_ui/img_tuna_logo.c --width 250 --trim
  python tools/img2lvgl.py assets/icon.png tuna_ui/img_icon.c --width 24 --alpha

The C symbol is the output file name without extension (img_tuna_logo);
use it in the sketch with LV_IMG_DECLARE(img_tuna_logo).
Output is RGB565 little-endian (lv_conf: LV_COLOR_DEPTH 16, LV_COLOR_16_SWAP 0).
--alpha keeps transparency (3 bytes/px); without it the image is opaque (2 bytes/px).
--trim crops away near-black borders before resizing.
--mask extracts a light glyph from a flat dark background (e.g. an icon
screenshot) as white + alpha, so it can sit on any background colour.
"""
import argparse
import os

from PIL import Image


def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src")
    ap.add_argument("dst")
    ap.add_argument("--width", type=int, help="target width in px (keeps aspect ratio)")
    ap.add_argument("--alpha", action="store_true")
    ap.add_argument("--trim", action="store_true")
    ap.add_argument("--mask", action="store_true")
    args = ap.parse_args()

    img = Image.open(args.src).convert("RGBA")
    if args.mask:
        lum = img.convert("L")
        bbox = lum.point(lambda v: 255 if v > 128 else 0).getbbox()
        if bbox:
            pad = 2
            bbox = (max(bbox[0] - pad, 0), max(bbox[1] - pad, 0),
                    min(bbox[2] + pad, img.width), min(bbox[3] + pad, img.height))
            lum = lum.crop(bbox)
        lo = min(lum.getdata())
        alpha = lum.point(lambda v: max(0, v - lo) * 255 // max(1, 255 - lo))
        img = Image.new("RGBA", lum.size, (255, 255, 255, 0))
        img.putalpha(alpha)
        args.alpha = True
    elif args.trim:
        bbox = img.convert("L").point(lambda v: 255 if v > 12 else 0).getbbox()
        if bbox:
            img = img.crop(bbox)
    if args.width and args.width != img.width:
        h = round(img.height * args.width / img.width)
        img = img.resize((args.width, h), Image.LANCZOS)

    name = os.path.splitext(os.path.basename(args.dst))[0]
    w, h = img.size
    out = bytearray()
    for r, g, b, a in img.getdata():
        v = rgb565(r, g, b)
        out += bytes((v & 0xFF, v >> 8))
        if args.alpha:
            out.append(a)

    cf = "LV_IMG_CF_TRUE_COLOR_ALPHA" if args.alpha else "LV_IMG_CF_TRUE_COLOR"
    lines = [", ".join(f"0x{b:02x}" for b in out[i:i + 24]) for i in range(0, len(out), 24)]
    with open(args.dst, "w", newline="\n") as f:
        f.write(f"// Generated by tools/img2lvgl.py from {os.path.basename(args.src)} - do not edit.\n")
        f.write('#include "lvgl.h"\n\n')
        f.write(f"static const LV_ATTRIBUTE_MEM_ALIGN uint8_t {name}_map[] = {{\n  ")
        f.write(",\n  ".join(lines))
        f.write("\n};\n\n")
        f.write(f"const lv_img_dsc_t {name} = {{\n")
        f.write(f"  .header.cf = {cf},\n  .header.always_zero = 0,\n  .header.reserved = 0,\n")
        f.write(f"  .header.w = {w},\n  .header.h = {h},\n")
        f.write(f"  .data_size = {len(out)},\n  .data = {name}_map,\n}};\n")
    print(f"{args.dst}: {name} {w}x{h} {cf} {len(out)} bytes")


if __name__ == "__main__":
    main()
